### ISSUE TITLE
get_footer is missing from page.php

### ISSUE THREAD

**Issue by bel-caylor** [gregsullivan/_tw#10]
I was troubleshooting why some plugin scripts weren't getting loaded and I discovered that 
`get_footer(); `
is missing from the page.php

**Comment by giorgioriccardi** [comment]
it is there:
[get_footer()](https://github.com/gregsullivan/_tw/blob/master/theme/page.php#L38)

Maybe a different issue caused the issue or a deleted string?

**Comment by giorgioriccardi** [comment]
oh yeah, welcome into our world ;-) I guess the issue can be marked as resolved.
Good luck!

**Comment by gregsullivan** [comment]
Thanks to both of you!
