### ISSUE TITLE
Issue with output Tailwind class grid-col-2 and above

### ISSUE THREAD

**Issue by blijonline** [gregsullivan/_tw#102]
Hi,

I'm trying to make a grid layout in the content-single.php file. But when I'm trying to use grid-cols-2 and above, there is no output CSS class for it.

When I use, for example, `<div class="grid grid-cols-1"> ... </div>` I see as output:  

.grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
}
.grid {
    display: grid;
}

But when I use, for example,  `<div class="grid grid-cols-2"> ... </div>` I see as output:

.grid {
    display: grid;
}

So the whole .grid-cols-2 class is not visible.

Do you have any idea how this is possible and how to solve it? 

Thanks in advance!

**Comment by blijonline** [comment]
Problem is solved, I made a typo in the theme.json file..

**Comment by gregsullivan** [comment]
Glad you were able to sort this out—please don't hesitate to post again if you encounter any other issues!
