### ISSUE TITLE
Error in the latest version

### ISSUE THREAD

**Issue by HugoCebrian** [gregsullivan/_tw#104]
Hey! I have just downloaded a new package to move my WIP website to it and i realized that there is a new error while using npm run watch.

✘ [ERROR] Could not resolve "./javascript/tailwind-typography-classes.js"

**Comment by gregsullivan** [comment]
Hello—Thanks for posting this!

Unfortunately, I can't duplicate this issue. The one way I could see it happening would be if you took the most recent version and merged it with an older project without updating the `package.json` file.

In the older `package.json` file, you'll find this line:

```json
"development:esbuild": "npx esbuild ./javascript/script.js ./javascript/block-editor.js ./javascript/tailwind-typography-classes.js --target=esnext --bundle --outdir=./theme/js --out-extension:.js=.min.js",
```

Replacing it with this should resolve the error:

```json
"development:esbuild": "npx esbuild ./javascript/script.js ./javascript/block-editor.js --target=esnext --bundle --outdir=./theme/js --out-extension:.js=.min.js",
```

Ideally you should always use the `package.json` file corresponding with the download to avoid similar issues.

I committed this change here:

https://github.com/gregsullivan/_tw/commit/3d7fc0d6f9219f2c55dc33aa31167a3eb57520af

It should likely have been a separate commit to flag that it wasn't part of the npm depedency updates.

Please let me know if that solves your issue, if it remains ongoing, or if you're able to duplicate it with an unmodified download.

Thanks again!

**Comment by HugoCebrian** [comment]
Ahaa! it makes all sense! 

I was going crazy with this project of mine and decided to start from scratch and clean it from the issues i was facing. I didn't realize that there was an update on the package. It was pushed by you only 10 minutes before i decide to generate it.

Thanks for replying so fast. Love this project immensily 🫡

**Comment by gregsullivan** [comment]
You're very welcome—happy to help! I was keeping an eye out for issues since I had broken the "don't deploy on Fridays" rule, so this was good timing.

Best of luck with your project!
