### ISSUE TITLE
Huge RAM/DIsk usage when running watchers for an extended period

### ISSUE THREAD

**Issue by dholly** [gregsullivan/_tw#114]
I'm experiencing a significant memory leak issue when running the development watchers (npm run watch). The memory usage grows tremendously over time, even though the watchers are running smoothly initially:

![Taskmgr_7ipJuO7T7N](https://github.com/gregsullivan/_tw/assets/5488213/6f5d7695-f4f6-4be7-840b-40ff87303a1d)

I have also tried running the watchers individually (`watch:tailwind:frontend`, `watch:tailwind:editor`, etc.) to isolate the culprit, but the memory leak seems to occur regardless of which watchers are running.

Does anyone else experience such an issue, or is it a local?

**Comment by gregsullivan** [comment]
Hi—Thanks for posting this!

I haven't personally experienced any issues of this sort, and I've left watch scripts running for days at times. But that certainly doesn't mean an issue doesn't exist! Some questions for you:

- What operating system are you using?
- What Node.js version are you using?
- Could you please provide the `content` value from your `tailwind.config.js` file?
- Do you encounter memory leaks with the non-Tailwind watchers (like the esbuild one, for example)?

There is a [Tailwind issue](https://github.com/tailwindlabs/tailwindcss/issues/7449) with some memory leak discussion, though possibly not relevant in this case.

**Comment by dholly** [comment]
Hi, thanks for reply!

**Operating System:**  Windows 10.
**Node.js Version:** 20.12.2.
**Tailwind.config.js:**
```
// Set the Preflight flag based on the build target.
const includePreflight = 'editor' === process.env._TW_TARGET ? false : true;

module.exports = {
    presets: [
        // Manage Tailwind Typography's configuration in a separate file.
        require('./tailwind-typography.config.js'),
    ],
    content: [
        // Ensure changes to PHP files and `theme.json` trigger a rebuild.
        './theme/**/*.php',
    ],
    theme: {
        // Extend the default Tailwind theme.
        extend: {
            fontFamily: {
                'bebas': ['Bebas Neue Pro', 'sans-serif'],
                'damn': ['DAMN', 'sans-serif'],
                'montserrat': ['Montserrat', 'sans-serif'],
            },
            fontWeight: {
                'normal': 400,
                'seminormal': 450,
                'medium': 500,
                'bold': 700,
                'expbold': 750,
                'expanded': 800,
                'extra': 850
            }
        }
    },
    corePlugins: {
        // Disable Preflight base styles in builds targeting the editor.
        preflight: includePreflight,
    },
    plugins: [
        // Add Tailwind Typography (via _tw fork).
        require('@_tw/typography'),

        // Extract colors and widths from `theme.json`.
        require('@_tw/themejson'),

        // Uncomment below to add additional first-party Tailwind plugins.
        // require('@tailwindcss/forms'),
        // require('@tailwindcss/aspect-ratio'),
        // require('@tailwindcss/container-queries'),
    ],
};
```
**Memory Leaks in Other Watchers:** I did not encounter memory leaks with other watchers.

In my opinion, these leaks are unlikely related to the theme itself, but it's the first and only time i've encountered such an issue. I've searched for a solution/cause for two days and just wanted to be sure and see if perhaps i'm not the only one experiencing this.

**Comment by gregsullivan** [comment]
Do you have any third-party PHP libraries inside your `./theme` directory? (Like if you were to add a `composer.json` file to that folder and install Composer packages for use in your theme.)

**Comment by dholly** [comment]
No, i've met it on just a fresh theme with only added fonts and some templates with a few blocks, no third-party php/js

**Comment by gregsullivan** [comment]
Two more possibilities:

- Unusual characters in the path to your repository (e.g., parentheses) have been known to cause issues
- Having your repository inside Dropbox (or similar) I believe has been known to cause issues as well

You also say you've never encountered an issue like this before; have you used Tailwind's CLI on other projects?

**Comment by dholly** [comment]
Alright, i found the cause.
I tried using the watchers outside of my phpstorm IDE’s built-in terminal - in windows cmd and then in the vscode terminal, and i didn’t notice any memory leaks at all, while in phpstorm the memory usage was increasing slowly but surely. 
It looks like the issue is related to the IDE or its plugin that i was using and is definitely local. 
I’m sorry for the inconvenience, and thank you for your time!

**Comment by gregsullivan** [comment]
No problem at all—thanks for letting me know!

For whatever it's worth, I also use PhpStorm and its built-in terminal, and I've never encountered any memory leaks that I'm aware of, so it may be possible with a different configuration to make things work.

Good luck with your project!
