### ISSUE TITLE
lg:hidden not working with flex

### ISSUE THREAD

**Issue by MZOG** [gregsullivan/_tw#119]
Hi, I just downloaded theme and started to implement my own header.
So I have `<div class="flex lg:hidden">` and it should be hidden on lg screen but it's not.

Also I don't know why there is `!important` added to the flex property.
![image](https://github.com/gregsullivan/_tw/assets/6049772/cc009140-4134-4f25-8a6b-60e0f105c513)

I've searched all files for any `!important` but there is none. 
I'm a bit confused why it's not working.

**Comment by gregsullivan** [comment]
Hi Marcin—Thanks for posting this!

I think we can consider these are two separate issues:

* **`.flex` as `!important`:** Is this coming from the same `style.css` file as the `display: flex` below? It appears not, but I can't see the source file in your screenshot.
* **`lg:hidden` not working**: There are a number of possibilities here, and I would need to see your repository to confirm one way or another. It could be that you are loading a cached version of the file, and that cached version doesn't have the class. It could be that you haven't rebuilt the CSS. It could be that you've modified your Tailwind configuration with a different screen size, and so you aren't triggering `lg` at the expected screen size.

In terms of debugging, I would suggest reviewing the `style.css` to check whether the `lg:hidden` class is present. (You'll want to search for `lg\:hidden`.) If it's not, exit any watch process, run `npm run dev`, and check again.

Hope that helps! Please let me know about the above, and we can continue debugging.

**Comment by gregsullivan** [comment]
I'm going to close this issue for now, but if you're able to answer my questions above, I'd be happy to reopen it in the future!
