### ISSUE TITLE
why delete Alpine.js ?

### ISSUE THREAD

**Issue by productdevbook** [gregsullivan/_tw#12]

**Comment by gregsullivan** [comment]
I felt adding Alpine.js by default was too prescriptive given that the majority of people using the theme are focused on the Tailwind side. Fundamentally, I want _tw to be a basic WordPress starter theme, plus Tailwind.

I use Alpine.js in all of my projects, but I think a project that evangelizes for both Tailwind and Alpine.js together needs to be something separate, with the focus here being exclusively on WordPress + Tailwind.

**Comment by productdevbook** [comment]
Can you help me how to install alpine.js ?

I am writing a wordpress theme and php for the first time. I'm a vue and backend developer. When I see this, I want to write a theme. And you did great. Thank you so much.

**Comment by gregsullivan** [comment]
Please see my response to your other comment here:

https://github.com/gregsullivan/_tw/issues/9#issuecomment-1120659316

**Comment by productdevbook** [comment]
Thank you working :)
