### ISSUE TITLE
js dont generate 

### ISSUE THREAD

**Issue by productdevbook** [gregsullivan/_tw#13]
![image](https://user-images.githubusercontent.com/38668796/167345554-3bba270d-04c3-4365-90d1-26b31c291c82.png)

**Comment by gregsullivan** [comment]
I'll take a look at this tomorrow and get back to you!

**Comment by productdevbook** [comment]
Actually, it would be nicer if you bring typescript support.

**Comment by gregsullivan** [comment]
Based on your other posts, I think you resolved this. That said, if you want a function in the global scope, you need to do something like this:

```javascript
window.decodeHtml = function( html ) {
	const txt = document.createElement( 'textarea' );
	txt.innerHTML = html;
	return txt.value;
};
```

> Actually, it would be nicer if you bring typescript support.

[esbuild supports TypeScript](https://esbuild.github.io/content-types/#typescript), so it's possible for a developer to add TypeScript to his or her build process without, e.g., installing any new dependencies. I don't think I could be convinced to make TypeScript the default in the foreseeable future.
