### ISSUE TITLE
Screens config warning

### ISSUE THREAD

**Issue by Seelescript** [gregsullivan/_tw#131]
Hi, thanks for the great generator.

I have a warning when I use min-* and max-*

`<footer class="mt-[50px] max-[1199px]:mt-[35px] bg-[#f8f8fb] text-[#fff]"></footer>`
`<div class="min-[992px]:w-[25%] max-[991px]:w-full w-full px-[12px] footer-cat"></div`

the warning:
"warn - The `min-*` and `max-*` variants are not supported with a `screens` configuration containing objects."

in my config file I have:

`theme: {		
		screens: {
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1536px',
		},
},`

if I test this on a tailwind project, it work normally, so some plugin may be changing the screens config, do you have any idea?

**Comment by Seelescript** [comment]
I found the issue, a third party plugin was adding breakpoints, thanks

**Comment by gregsullivan** [comment]
Happy you were able to sort this out! In case anyone else encounters the issue, the pull request for this feature explains what will and won't work under the "Restrictions" heading:

https://github.com/tailwindlabs/tailwindcss/pull/9558
