### ISSUE TITLE
npm install is creating empty folders in node_modules?

### ISSUE THREAD

**Issue by SamuelAshbrook** [gregsullivan/_tw#133]
Hi. I have attempted to install the _tw theme however, when I try to execute "npm install" it creates empty folders within the node_modules folder.

If I then execute the "npm run dev" command, I am given the error "run-p' is not recognized as an internal or external command, operable program or batch file.".

Is there a way that I could resolve this issue? I have the latest LTS version of Node.js.

![image](https://github.com/user-attachments/assets/1e3953be-fa39-4d53-a440-12e900f1ec2f)

![image](https://github.com/user-attachments/assets/7cbee788-ec15-4ec9-8e04-d3ea398e7dcc)

**Comment by SamuelAshbrook** [comment]
Here is a similar thread: https://github.com/gregsullivan/_tw/discussions/67. I am also using LocalWP so wondering if this may be causing the issue?

**Comment by SamuelAshbrook** [comment]
Managed to fix this by reloading localwp.

**Comment by gregsullivan** [comment]
Hi Samuel—Glad you were able to get this sorted! (And sorry for the delay in responding—I was out sick last week.)

I'll keep my eye on this, but I'm still unsure what it is about Local WP that sometimes causes `npm install` to fail without notice. If you have any further insights, I'd love to hear them.

Thanks again!

**Comment by gregsullivan** [comment]
For anyone finding this in the future, I think this may be related:

https://community.localwp.com/t/change-to-node-env/43176

It suggests setting `NODE_ENV` to development may solve the problem.

### macOS / Linux

`export NODE_ENV=development`

### Windows

`set NODE_ENV=development`

(I don't have a Windows machine, so if someone knows the above to be wrong, please let me know!)
