### ISSUE TITLE
Getting 'undefined' when using inline script in combination with the script.js file

### ISSUE THREAD

**Issue by luuktimmermans** [gregsullivan/_tw#134]
### Discussed in https://github.com/gregsullivan/_tw/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **luuktimmermans** September  4, 2024</sup>
Hi,

I'm using the following javascript plugin for a typewriter effect: [https://github.com/tameemsafi/typewriterjs](https://github.com/tameemsafi/typewriterjs).

I've done everything as explained in the docs, but I'd like to use the typewriter.typestring.... part inline in a file. When doing this I get `Uncaught ReferenceError: typewriter is not defined`. This is due to the fact that the script.js gets added to the footer, so that means this gets loaded after the inline script. Is there a way to fix this? I need to use the script inline since I'm using ACF to get values that I'm using in the plugin.</div>

**Comment by gregsullivan** [comment]
I'm going to close this in favour of the discussion, as I don't believe this is a bug in _tw. I'd be happy to follow up if you think that it is!
