### ISSUE TITLE
Selective application of CSS classes in various scenarios

### ISSUE THREAD

**Issue by Andersang** [gregsullivan/_tw#136]
There seems to be a selective application of CSS Classes, for some unknown reason. The most obvious of this is in the application of border styles to divs.

To reproduce, add this div to any part of the page:

``` html
<div class="border-t border-black">
test
</div>
```

You will find that no top border width has been applied. However, if you change `border-t` to `border-y`, you will find that now both the top and bottom border widths are applied. It seems like `border-t` has been ignored. 

There are also random quirks of similar nature, such as background colours not working in buttons, etc, and I have not been able to find all of them yet.

**Comment by gregsullivan** [comment]
Hi Anders—Thanks for posting this!

I just generated a fresh theme, ran `npm install` and `npm run watch`, and pasted your example `div` in `header.php`. Here is the result:

<img width="419" alt="Screenshot 2024-09-16 at 5 14 58 PM" src="https://github.com/user-attachments/assets/18c69d03-83cd-4a39-8d6f-6e4bca2e42b0">

My guess is that your `watch` process either wasn't running or had crashed, and the classes that were working (e.g., `border-y`) had been used previously in your project (so they already existed in your generated CSS).

I'd be happy to troubleshoot this with you further if you're able to provide more details, though! I'm going to close this pending any further updates.
