### ISSUE TITLE
Adding className under require plugin does not change prose class name 

### ISSUE THREAD

**Issue by andyfostertamu** [gregsullivan/_tw#138]
I added this:

require('@_tw/typography')({
	==> 	className: 'wysiwyg',
		  }),

according to this:

https://github.com/tailwindlabs/tailwindcss-typography?tab=readme-ov-file#changing-the-default-class-name

Didn't work. Any ideas?

**Comment by gregsullivan** [comment]
Hi Andy—Thanks for posting this!

Can you confirm that you've updated the classes you're using for Tailwind Typography to reflect the new class name? You'll find them at the top of `./theme/functions.php`:

https://github.com/gregsullivan/_tw/blob/fd500cc671105c5228e727b4b15236e38cbb0420/theme/functions.php#L21-L43

If you've added the `wysiwyg` and `wysiwyg`-prefixed classes and it's still not working, I'd need to see your repository to have a better sense of what is going on.

Hope that helps!

**Comment by andyfostertamu** [comment]
Oh that should work. Didn't think of looking at functions.php. *slaps forehead*. I'll check tomorrow and come back and close. Thanks

**Comment by gregsullivan** [comment]
Sounds great—please let me know if you run into any other issues!

**Comment by andyfostertamu** [comment]
Works. Gosh - I always forget to check the functions.php file! Thanks.

**Comment by gregsullivan** [comment]
You're very welcome—happy this is now working for you!
