### ISSUE TITLE
NPM Run Dev failing

### ISSUE THREAD

**Issue by shaunrobinson** [gregsullivan/_tw#139]
I'm currently developing a site and was adding another Alpine plugin and it all stopped working.

So I tried downloading a fresh new copy of _tw and running npm install then npm run dev and it fails with these messages:

```
npm run dev

> dev
> npm run development


> development
> run-p "development:**"


> development:esbuild
> npx esbuild ./javascript/script.js ./javascript/block-editor.js --target=esnext --bundle --outdir=./theme/js --out-extension:.js=.min.js


> development:tailwind:editor
> cross-env _TW_TARGET=editor npx tailwindcss --postcss -i ./tailwind/tailwind.css -c ./tailwind/tailwind.config.js -o ./theme/style-editor.css

sh: cross-env: command not found

> development:tailwind:frontend
> npx tailwindcss --postcss -i ./tailwind/tailwind.css -c ./tailwind/tailwind.config.js -o ./theme/style.css


> development:tailwind:editor:extra
> cross-env _TW_TARGET=editor npx tailwindcss --postcss -i tailwind/tailwind-editor-extra.css -c ./tailwind/tailwind.config.js -o ./theme/style-editor-extra.css

sh: cross-env: command not found
ERROR: "development:tailwind:editor" exited with 127.
```

Any idea how I can fix this? I have no idea, and work on my site has stalled until I can resolve this.

**Comment by shaunrobinson** [comment]
OK, I installed cross-env globally (never had to do that before) and now get a new error:

```
Error: Cannot find module 'postcss-import-ext-glob'
```

**Comment by shaunrobinson** [comment]
It seems what has happened is the node_modules folder just contains empty folders, no files. What could cause this?

**Comment by shaunrobinson** [comment]
Nevermind, was caused by updating my Mac, I have fixed it!

**Comment by gregsullivan** [comment]
Very happy you were able to sort this out! Please don't hesitate to create future issues if you run into any problems.
