### ISSUE TITLE
Why do I have to use Twind Shim 

### ISSUE THREAD

**Issue by andyfostertamu** [gregsullivan/_tw#140]
Installed and have it up and running.

It wouldn't recognize any Tailwind classes like underscore, shadow-2xl, etc 

So I had to use the twins shim in the header and it works.

But is there a reason behind this? I looked through the documentation and feel like I missed something?

Thanks

**Comment by gregsullivan** [comment]
Hello—thanks for posting this!

In what context are you using those classes—in your theme, or in the block editor?

_tw is designed to pick up classes in the theme. If they're not working there, please let me know and we can figure out what's going wrong!

If the classes are in the block editor, I've written a bit here about the philosophy of _tw and where Tailwind classes are recognized:

https://underscoretw.com/docs/why/

And this is the more general documentation about arbitrary classes:

https://underscoretw.com/docs/wordpress-tailwind/#arbitrary-classes

If you have any other questions, please let me know!

**Comment by andyfostertamu** [comment]
I use custom blocks from Genesis. I see the note about block editor and that it wouldn't work without shim or safelist. I'll use either option as we use some custom blocks with tailwind. Not a whole lot. 

I do use custom blocks with php template. I figure it should work in this manner (I haven't tried it but I'll probably use this option more) to ensure we can utilize Tailwind more. 

Thanks for the clarification.

**Comment by gregsullivan** [comment]
No problem at all! Happy it's working for you. Does Genesis allow the possibility of including a template file with your theme? That could potentially help as well. (I haven't used Genesis blocks for a while, as I generally only use it when a client has it installed already because I don't have a license of my own.)

**Comment by andyfostertamu** [comment]
Hi Greg - yes Custom blocks from Genesis allows me to develop php template files for complex operations (loops, database retrieval, etc). I'll just utilize this feature for all of the blocks to ensure Tailwind classes are called upon. Thanks!

**Comment by gregsullivan** [comment]
You're very welcome—and please don't hesitate to post future issues or discussions if you have other questions!
