### ISSUE TITLE
Issue with alpine.js not working in production

### ISSUE THREAD

**Issue by aydeeen** [gregsullivan/_tw#146]
An awesome starter theme!

I have only one issue. 
Basically I followed your steps and added alpine.js and it works perfectly in development.
But when I build it for prod, it doesn't register alpine.js at all. It's as there is no js at all.
Any help would be appreciated.

Thank you!

**Comment by aydeeen** [comment]
JS is compiled when I run build, I can see the files but when I check dev tools it's not there. 
![Screenshot 2024-11-16 151702](https://github.com/user-attachments/assets/ed0d27fe-8b9c-4162-82cb-e8781bcbef70)

**Comment by gregsullivan** [comment]
Hi Ajdin—Thanks for posting this!

Are you able to share your production URL?

Could you take a look at your Network tab in Chrome dev tools and filter by `script` to see whether it's showing up, but with a 404 error or something similar? It will end up looking something like this:

<img width="310" alt="Screenshot 2024-11-16 at 2 38 47 PM" src="https://github.com/user-attachments/assets/8e146209-8711-4a5d-9345-02f6843dd3aa">

Please let me know about the above, and we'll go from there!

**Comment by aydeeen** [comment]
Thank you for checking it!

I looked at the network tab and there is no js script at all there.
I don't have prod url yet but I created test instance locally to test it.
Can maybe zip file of the prod help you to check it?
[ple.zip](https://github.com/user-attachments/files/17791103/ple.zip)

**Comment by gregsullivan** [comment]
I installed it in a cloud staging site, and it errored out before displaying the footer. Could you please confirm that when you view source in production, you're seeing all the way to the `</html>` tag to end the page? (The `script.js` file is loaded in the footer, so if there's an error before then, that would stop the file from loading.)

**Comment by gregsullivan** [comment]
I installed ACF Pro to remove the errors. I'm seeing the `script.js` file loading:

<img width="310" alt="Screenshot 2024-11-18 at 11 56 59 AM" src="https://github.com/user-attachments/assets/e3efd1ed-72d6-449e-b903-d81e142f8edd">

Are you sure you're not blocking it with a script blocker of some kind? Do you see a line like this at the bottom of your HTML:

```
<script src="https://domain.test/wp-content/themes/ple/js/script.min.js?ver=sn1rts" id="ple-script-js"></script>
```

If you don't, I would guess a plugin is removing or overriding it.

**Comment by aydeeen** [comment]
Thank you for finding time to check it.
I don't have basically any js file in the footer, it completely devoid of any script so its really weird.
And of the plugins, I only have ACF installed, nothing else.

**Comment by gregsullivan** [comment]
Can you please send a screenshot of the bottom of your page source? (Not from dev tools, but from View > Developer > View Source.)

**Comment by aydeeen** [comment]
I have found the culprit.
There was one ACF field in the footer which needed to be populated because I haven't added if/else check there. 
And basically that silent background error stopped the small part of the footer from compiling and that included scripts.
Sorry for bothering you with this and thank you so much for having time to solve this with me 🙂

**Comment by gregsullivan** [comment]
No problem at all—good luck with your project!

**Comment by aydeeen** [comment]
Thank you man!
Much appreciated for the help with this and sorry again because I should have been more careful with those fields.
I will add you on linkedin so that we can connect.
Cheers!
