### ISSUE TITLE
Theme is missing the style.css stylesheet

### ISSUE THREAD

**Issue by KodyKendall** [gregsullivan/_tw#155]
I generated a theme from _tw, and when I tried to upload the zip to my Wordpress instance, I got this error:

<img width="603" alt="Screenshot 2024-12-02 at 9 44 01 AM" src="https://github.com/user-attachments/assets/914aeda3-603a-4cc5-9953-bfe4e8a386a9">

**Comment by gregsullivan** [comment]
Hi Kody—Thanks for posting this!

Are you uploading the zip file directly from the generator? The steps to install it locally are:

1. Unzip the archive
2. Move the entire unzipped folder to wp-content/themes in your local WordPress installation
3. Run npm install && npm run dev in the moved folder
4. Activate the theme in your local WordPress installation

Then, once you're ready to deploy to a production server, you could potentially use `npm run bundle` to generate an upload-ready zip file, and you could upload that zip file using the "Add Theme" interface in WordPress.

Please let me know if I'm misunderstanding, though!

**Comment by gregsullivan** [comment]
I'm going to close this for now, but please feel free to check back in and reopen it if you're still experiencing this issue!
