### ISSUE TITLE
CSS variable "bg-background" missing by default

### ISSUE THREAD

**Issue by Maxtab** [gregsullivan/_tw#16]
Hi and first, many thanks for your theme generator.

It seems that, out of the box, one of the CSS reference is missing, because, when doing "npm run watch", I have this message : 
CssSyntaxError: tailwindcss: /****UNUSEFUL THEME PATH*****/wp-content/themes/*****THEME SLUG****/tailwind/custom/base.css:15:2: The `bg-background` class does not exist. If `bg-background` is a custom class, make sure it is defined within a `@layer` directive.

So I think it is refering to the palette mentionned in the theme.json file.

Adding the missing "bg-background" (instead of "background" which is already present) fix this.

**Comment by gregsullivan** [comment]
Hello! You're very welcome—thanks for posting this issue.

I just downloaded a fresh build, ran `npm install && npm run watch`, and everything worked as expected.

Are you able to share your theme repository?

The `bg-background` class uses the color with the `background` slug in `theme.json`. You could similarly use `bg-primary` or `bg-foreground`, as the `bg-` prefix comes from Tailwind itself, with the appended color coming from the `theme.json` file by way of the `tailwind.config.js` file.

**Comment by Maxtab** [comment]
Sorry for the delay, I was searching the reason for this message on my side. You're right, it was not out of the box, so it comes from me, sorry.

And, of course, I do not have a commit prior this as I was in the very early dev stage.

So I close the ticket, as there is nothing to fix on your side ! :)

**Comment by gregsullivan** [comment]
No problem at all—thanks for the update!
