### ISSUE TITLE
style.css build missing some parts since last update (Postcss import related?)

### ISSUE THREAD

**Issue by Maxtab** [gregsullivan/_tw#18]
Hi,

I tried on a freshly new downloaded theme, using the generator on the website, it seems that the generated style.css file is missing the header and the custom font css file when using the npm run watch command.

Maybe something related the removal of postcss import ?

**Comment by gregsullivan** [comment]
Good catch, thanks for this!

It was a combination of issues surrounding `postcss-import`, `postcss-simple-vars` and Tailwind Typography, now resolved. Sorry for not catching this sooner!

**Comment by Maxtab** [comment]
Thank you for your quick fix and answer. Anychance we see the changes in a commit to correct this on my already generated theme? 

Again, thank you for your great tool. Wish you a great success with this !

**Comment by gregsullivan** [comment]
My apologies—in my haste, I updated the generator, but committed the change to a local branch when updating this repository. Here is the commit:

https://github.com/gregsullivan/_tw/commit/1c370a19c9fa2b65a7906ff0f2c4b9c53638ceb1
