### ISSUE TITLE
Function isnt added to script.min.js

### ISSUE THREAD

**Issue by CGTS** [gregsullivan/_tw#19]
I'm importing Alpine JS in `javascript/script.js` but the function in the same file is not getting pulled into the scripts.min.js. I'm not sure if I'm missing something. I've checked and Alpine is getting added just not the function. Any help is appreciated. 

Below is what I have in the scripts file.

```import Alpine from 'alpinejs'
 
 window.Alpine = Alpine
  
 Alpine.start()

//  Navigation Scroll Effects
function scrollToReveal() {
  return {
    sticky: !1,
    lastPos: window.scrollY + 0,
    pageStart: !0,
    topPos: 0,
    scroll() {
      this.sticky = window.scrollY > this.$refs.navbar.offsetHeight && this.lastPos < window.scrollY,
      this.lastPos = window.scrollY,
      this.pageStart = window.scrollY < this.$refs.navbar.offsetHeight > window.scrollY
    }
  }
}```

**Comment by gregsullivan** [comment]
Hi—Thanks for posting this!

This looks like more of an esbuild issue than an _tw issue. That said, when you're adding functions to be handled by esbuild, you'll need to put them to the global object if you want them to be available in the way you're expecting. I think this would work for you:

```javascript
//  Navigation Scroll Effects
window.scrollToReveal = function() {
  return {
    sticky: !1,
    lastPos: window.scrollY + 0,
    pageStart: !0,
    topPos: 0,
    scroll() {
      this.sticky = window.scrollY > this.$refs.navbar.offsetHeight && this.lastPos < window.scrollY,
      this.lastPos = window.scrollY,
      this.pageStart = window.scrollY < this.$refs.navbar.offsetHeight > window.scrollY
    }
  }
}
```

(This is necessary for the same reason that writing `window.Alpine = Alpine` is necessary.)

------

I think there's a case to be made that this would be worth adding to the documentation for anyone new to JavaScript bundlers generally and esbuild specifically.

**Comment by gregsullivan** [comment]
I went ahead and expanded the documentation surrounding esbuild:

https://underscoretw.com/docs/tailwind-plugins-npm-commands/#javascript

Please let me know if you have any suggestions on how this could be improved!

**Comment by CGTS** [comment]
Thanks for the help. I'll take a look at the documentation.
