### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by vexsolutions** [gregsullivan/_tw#2]
Brand new install of the project. Attempt to run `npm run dev` throws the error. I tried installing @babel/core manually but the error persists. Have been googling for hours with no resolution. Any help would be immensely appreciated. 

error stack

[webpack-cli] Error: Cannot find module '@babel/core'
Require stack:
C:\<path to project>\node_modules\laravel-mix\src\FileCollection.js
C:\<path to project>\node_modules\laravel-mix\src\tasks\ConcatenateFilesTask.js
C:\<path to project>\node_modules\laravel-mix\src\components\Combine.js
C:\<path to project>\node_modules\laravel-mix\src\components\ComponentRegistrar.js
C:\<path to project>\node_modules\laravel-mix\src\Mix.js
C:\<path to project>\node_modules\laravel-mix\setup\webpack.config.js
C:\<path to project>\node_modules\webpack-cli\lib\webpack-cli.js
C:\<path to project>\node_modules\webpack-cli\lib\bootstrap.js
C:\<path to project>\node_modules\webpack-cli\bin\cli.js
C:\<path to project>\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (C:\<path to project>\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\<path to project>\node_modules\laravel-mix\src\FileCollection.js:4:13)
    at Module._compile (C:\<path to project>\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\<path to project>\\node_modules\\laravel-mix\\src\\FileCollection.js',
    'C:\\<path to project>\\node_modules\\laravel-mix\\src\\tasks\\ConcatenateFilesTask.js',
    'C:\\<path to project>\\node_modules\\laravel-mix\\src\\components\\Combine.js',
    'C:\\<path to project>\\node_modules\\laravel-mix\\src\\components\\ComponentRegistrar.js',
    'C:\\<path to project>\\node_modules\\laravel-mix\\src\\Mix.js',
    'C:\\<path to project>\\node_modules\\laravel-mix\\setup\\webpack.config.js',
    'C:\\<path to project>\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\<path to project>\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\<path to project>\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\<path to project>\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

package.json

{
	"private": true,
	"devDependencies": {
		"@babel/core": "^7.14.3",
		"@babel/preset-env": "^7.14.2",
		"@tailwindcss/aspect-ratio": "^0.2.0",
		"@tailwindcss/forms": "^0.3.2",
		"@tailwindcss/line-clamp": "^0.2.0",
		"@tailwindcss/typography": "^0.4.0",
		"@wordpress/eslint-plugin": "^9.0.4",
		"@wordpress/stylelint-config": "^19.0.3",
		"archiver": "^5.3.0",
		"cross-env": "^7.0.3",
		"laravel-mix": "^6.0.18",
		"postcss-import": "^14.0.1",
		"tailwindcss": "^2.1.2"
	},
	"scripts": {
		"dev": "npm run development",
		"development": "cross-env TAILWIND_MODE=build mix",
		"watch": "mix watch",
		"watch-poll": "mix watch -- --watch-options-poll=1000",
		"prod": "npm run production",
		"production": "mix --production",
		"bundle": "npm run prod && node scripts/bundle.js rttsolutions"
	},
	"dependencies": {
		"eslint": "^7.26.0",
		"postcss": "^8.2.15",
		"prettier": "^2.3.0",
		"stylelint": "^13.13.1",
		"typescript": "^4.2.4"
	}
}

**Comment by adrianvalenz** [comment]
Did you attempt to get it running by cloning this repo, or did you use the generator at https://underscoretw.com ?

**Comment by vexsolutions** [comment]
@adrianvalenz I used the generator.

**Comment by vexsolutions** [comment]
After running into this issue with other projects I was sure there error had to do with my environment and not this package. I completely rebuilt node and that resolved the issue.

**Comment by gregsullivan** [comment]
Sorry for the very late response on this—I'm embarrassed to admit my GitHub notification settings were incorrect, and I only saw your issue today.

I'm happy to hear this was resolved!
