### ISSUE TITLE
Flowbite support

### ISSUE THREAD

**Issue by mmdevapp** [gregsullivan/_tw#21]
I develop a theme based on the tailwind plugin flowbite. It's working well except inside the gutenberg editor. 

I added the script.min.js with a admin_head hook.

This is my javascript/script.js:
```
import 'flowbite';
window.flowbite
```

tailwind.config.js:
```
	content: [
		// Ensure changes to PHP files and `theme.json` trigger a rebuild.
		"./node_modules/flowbite/**/*.js",

and

	plugins: [
		require('flowbite/plugin')
```

Is there a way to make it work?

**Comment by gregsullivan** [comment]
Thanks for posting this issue!

Could you provide more detail on what you're expecting to see in the Gutenberg editor, and what you're seeing instead?

What was your goal in including the `.js` files under the `content` key in `tailwind.config.js`?

(I haven't used Flowbite before, so I want to make sure I'm not misunderstanding anything.)

**Comment by gregsullivan** [comment]
I'm going to close this issue pending further feedback. If you provide feedback, I would be happy to reopen!
