### ISSUE TITLE
Recommended approach for dynamic blocks

### ISSUE THREAD

**Issue by rogercoathup** [gregsullivan/_tw#22]
@gregsullivan  -- is there a recommended approach for dynamic blocks, using Tailwind in their PHP markup, and getting it to build as part of my _tw theme?

**Comment by gregsullivan** [comment]
Thanks for posting this issue!

Is the PHP markup for your dynamic blocks part of your theme, or does that markup exist elsewhere?

**Comment by rogercoathup** [comment]
It would be a separate plugin.  However, I've just thought I could implement with template overrides in the theme -- so, plugin could stay neutral, but the overrides in the theme could embed the tailwind markup.

**Comment by gregsullivan** [comment]
That would work! (And is likely the most straightforward approach.)

Fundamentally, you just need some way to put the Tailwind classes in your theme repository where Tailwind can pick them up. If it's a custom plugin, you could base it out of a shared repository with the theme, though that would require changes to the existing build process. You could safelist the classes manually, but that wouldn't be fun in terms of ongoing maintenance.

You could also create a separate build process using Tailwind for the plugin and include that CSS file as well, though you'd likely end up with some duplicate classes.

I'm going to close this, but please let me know if you have any other questions!

**Comment by rogercoathup** [comment]
Yes, please close, and thanks for quick responses... much appreciated.

**Comment by gregsullivan** [comment]
No problem at all—thanks for using _tw!
