### ISSUE TITLE
Why Varia?

### ISSUE THREAD

**Issue by tareiking** [gregsullivan/_tw#23]
Hi @gregsullivan - just been lurking on your theme development as we weigh up the shift to tailwind.css for our own workflow.

But something I haven't quite found clearly written up yet (granted, its only been a recent changelog entry) is a little bit of insight into why you have chosen to implement parts of [Varia](https://github.com/Automattic/themes/tree/trunk/varia) theme into the base theme?

I don't have an opinion for or against, just a curiosity as to your thoughts here as a developer.

🍰 🎁  for all your work to date!

**Comment by rawalplawit** [comment]
@gregsullivan mentioned the Varia theme in  the May release note.

Here's what he said.
> In search of a new theme to use as a basis for _tw, I found [Varia](https://github.com/Automattic/themes/tree/trunk/varia) via [this comment on GitHub](https://github.com/Automattic/_s/issues/1369). Varia seems to be as close to an Underscores successor as exists at Automattic and receives ongoing maintenance.

From what I can find, Varia is the theme used internally and is used by Automattic as a [parent theme](https://wordpress.com/theme/varia) for their Wordpress.com saas. 

Complete link at https://underscoretw.com/release-notes/may-2022/#h-drawing-from-varia

**Comment by tareiking** [comment]
Oh nice. I actually missed the threaded discussion in that release note. Thanks ;)

**Comment by gregsullivan** [comment]
Thanks to both of you—feels like my work here is done! This has made me realize, though, that the previous release notes don't link directly to the appropriate comment:

https://github.com/Automattic/_s/issues/1369#issuecomment-529716734

(I've updated the link in the release notes.)

I also realized last week that I need to overhaul the FAQ on the underscoretw.com homepage, so I’m going to do that alongside the new release notes, and I'll add a bit of context about Varia there.

Fundamentally, Varia’s template HTML has had more eyes on it over the years, and you really start to feel the cumulative effects of that effort when you work with it. Its integration with WordPress also takes into account changes from more recent releases, and it gives me a single repository I can watch, knowing I won't miss anything important from a theme perspective in a new version of WordPress.

A year or two from now, it might make sense to look at things from the perspective of full-site editing and see whether a hybrid theme still makes sense, but I don't think we're there yet.

I'll close this issue, but I’d also be happy to continue the discussion!

**Comment by gregsullivan** [comment]
I've published a [release note for the most recent round of changes](https://underscoretw.com/release-notes/september-2022/) with more details on the improvements from Varia, and I've also begun linking to the release notes from the [changelog](https://github.com/gregsullivan/_tw#changelog) on GitHub.

I'll make more of an effort in the future to publish release notes simultaneously with major commits to GitHub!
