### ISSUE TITLE
Add info on how to use a Custom CSS with Tailwind

### ISSUE THREAD

**Issue by VoidElle** [gregsullivan/_tw#29]
In the dev documentation, there isn't a section explaining how to use a custom css, every modification of the style.css or style-editor.css on executing the command "npm run watch" or "npm run dev" gets overwritten.

**Comment by gregsullivan** [comment]
Hi Luca—Thanks for opening this issue!

I'll add some details about this to the documentation. Just to get you started, the basic idea is that those two files are generated by Tailwind; if you want to add code to them, you do so via files in the `./tailwind` folder. The `./tailwind/tailwind.css` file is the root file that references a variety of other files to create the two generated files. There are also two Tailwind config files that control other elements of what ends up in `style.css` and `style-editor.css`.

Please let me know if you have any other questions, and I'll let you know when I've added a note to the documentation so you can tell me whether it adequately answers your question.

**Comment by VoidElle** [comment]
Hey Greg thanks for the fast reply,
sorry for the question but these are my first experiences with tailwind.
Tried, worked!

Love your project btw

**Comment by gregsullivan** [comment]
Hi Luca,

This is very belated, but I've updated the documentation based on your feedback:

https://underscoretw.com/docs/development/#custom-css

I'm going to close this issue, but I'd love to hear any feedback you have on the wording, and whether there's something I could add that would have helped you when you first encountered this issue.

Thanks again!
