### ISSUE TITLE
classes in editor blocks not compiled

### ISSUE THREAD

**Issue by jmyt8** [gregsullivan/_tw#3]
Hi, I was testing the theme and it works well with templates, but utitlity classes added in glutenberg blocks or html blocks don't get compiled. Is there any solution for this?

Great theme!

**Comment by gregsullivan** [comment]
Sorry for the late response on this—I'm embarrassed to admit my GitHub notification settings were incorrect, and I only saw your issue today.

Unfortunately, the nature of Tailwind's purge process (see Tailwind's documentation on [Optimizing for Production](https://tailwindcss.com/docs/optimizing-for-production) for details) makes it less than ideal if you'd like to use utility classes within the block editor.

One workaround would be to [create a safelist](https://tailwindcss.com/docs/optimizing-for-production#safelisting-specific-classes) of classes that you want to use in the block editor, which will prevent them from being purged. But if you'd like to be able to use arbitrary Tailwind classes in the block editor without limits, the only option would be not to use purging, which would result in a very large CSS file.

Hope that helps—please let me know if you have any other questions!
