### ISSUE TITLE
Theme is installed but incomplete

### ISSUE THREAD

**Issue by justinluk** [gregsullivan/_tw#31]
After I've run `npm install && npm run dev` Wordpress isn't able to activate the theme because it says that the stylesheet is missing. I'm not sure what I'm doing wrong here.

Here's a screenshot of my file structure. 

![Screen Shot 2022-12-07 at 10 22 15 AM](https://user-images.githubusercontent.com/158645/206219011-ae7f9745-a11b-4bb4-89c3-cd76e0b833eb.png)

Do you have any advice on how to fix this?

**Comment by justinluk** [comment]
This is what's inside my theme folder

![Screen Shot 2022-12-07 at 10 23 11 AM](https://user-images.githubusercontent.com/158645/206219280-f8a99841-e6c8-44ac-8135-fba2d40ccf62.png)

**Comment by gregsullivan** [comment]
Hi Justin—thanks for posting this issue!

Could you please take a screenshot of the error you're seeing in WordPress?

Thanks very much!

**Comment by gregsullivan** [comment]
Actually, could you also show me the top of your `style.css` file?

**Comment by justinluk** [comment]
Definitely, here you go!

![Screen Shot 2022-12-08 at 9 23 29 AM](https://user-images.githubusercontent.com/158645/206470971-f84e02cc-b063-4f2b-b185-0267624f3dd0.png)

**Comment by gregsullivan** [comment]
Okay, that looks good to me! Could you send me a screenshot of the error?

What are you using to serve the site locally?

I just tested development installation in WordPress 6.1.1, and it worked as expected, so it's not a change in WordPress causing the problem.

**Comment by justinluk** [comment]
<img width="1233" alt="Screen Shot 2022-12-08 at 9 40 11 PM" src="https://user-images.githubusercontent.com/158645/206611832-38c9aa02-5a7a-4991-9ef1-20d839341657.png">

This is the error I'm getting, I'm using Docker with the latest Wordpress image, 6.1.1. I have a volume setup so the files in the container are on my computer. Ooooh but as I'm saying that, it appears that the files on the host aren't being copied to the container. Haha looks like a Docker issue on my end. Sorry!

**Comment by gregsullivan** [comment]
Thanks for the update—glad you got it sorted!
