### ISSUE TITLE
Subpackage eslint-plugin-jsdoc version not compatible with node 18+

### ISSUE THREAD

**Issue by scheinercc** [gregsullivan/_tw#32]
Hey Greg, that is more of an FYI ticket

https://github.com/WordPress/gutenberg/issues/46386

**Comment by gregsullivan** [comment]
Thanks for this! If I have time next week, I'll try to take a deeper look to see what needs to be done to push this forward. I think the blocker right now is the extent of the code changes required to make the update absent configuration changes.

**Comment by gregsullivan** [comment]
@scheinercc I've spent some more time looking into this, and I'm beginning to wonder if this will end up being a choice between supporting either `@wordpress/eslint-plugin` or the latest LTS version of Node, at least for the medium term. (I no longer think there's a configuration option that will prevent changes throughout Gutenberg as a consequence of this version change, but I'd love to be proven wrong.)

I suspect I'd come down on the side of supporting more recent versions of Node, and basically following this proposal:

https://make.wordpress.org/core/2022/01/05/proposal-changes-to-javascript-coding-standards-for-full-prettier-compatibility/

What do you think?

**Comment by scheinercc** [comment]
> I suspect I'd come down on the side of supporting more recent versions of Node, and basically following this proposal:

Sounds good to me. I support Greg's reasoning as well and am more used to the default Prettier styling for JS anyway. Thanks for looking into it!

**Comment by gregsullivan** [comment]
Okay, great! I was thinking of simply swapping `plugin:@wordpress/eslint-plugin/esnext` for `eslint:recommended` as the value for `extends` and letting people add plugins as their project demands.

Do you see any issues with that approach?

**Comment by scheinercc** [comment]
> Do you see any issues with that approach?

Nope.

**Comment by gregsullivan** [comment]
I'm hoping to move forward with this later this week!

**Comment by gregsullivan** [comment]
I finally got around to making this change:

https://github.com/gregsullivan/_tw/commit/64b724efa45ad48e77506ee9a0013efb9257d6f8

I'm going to close this issue, but if you have any feedback, please let me know!

**Comment by scheinercc** [comment]
Awesome. Thanks Greg!

**Comment by gregsullivan** [comment]
You're very welcome—thanks again for reporting the issue!
