### ISSUE TITLE
Modifiying fonts

### ISSUE THREAD

**Issue by luckyth13teen** [gregsullivan/_tw#33]
Not completely understanding the how to set the default settings for font families for H-all and html from looking at the existing code. I am sure this is due to a lack of familiarity with tailwind +theme,json but your default doesn't match tailwinds default settings as far as I understand it with the call to (theme). 

Is the expected modification supposed to happen in custom a css change, a theme.json change, or a tailwind css change?

want to work with the tool and not against it so I am trying to use this the intended way from the start.

**Comment by gregsullivan** [comment]
Hi Kevin—thanks for posting this issue!

The `theme.json` file is specific to WordPress, and the only values we import over to Tailwind are colours and content width.

Fonts should all be set up within Tailwind. This is likely the best overview from their documentation:

https://tailwindcss.com/docs/font-family

_tw defaults to `font-sans` applied to the `body` element:

https://github.com/gregsullivan/_tw/blob/master/tailwind/custom/base.css

If you're specifically looking to change font size / weight within the editor, you'll want to modify this file:

https://github.com/gregsullivan/_tw/blob/master/tailwind/tailwind-typography.config.js

I'm working on an approach that will allow [Tailwind Typography's element modifiers](https://tailwindcss.com/docs/typography-plugin#element-modifiers) to be used alongside that file, but I don't expect that to be complete until the New Year.

Please let me know if you have any other questions!

**Comment by luckyth13teen** [comment]
Appreciate the clarifications!

Theme.json seems poised to be used as a the variable definer from wordpress in the future in some ways so I am constantly trying to make sure the "old" way of using css to control it isn't fighting an existing new setup from wordpress. The injected styles from gutenburg blocks is becoming more and more a pain to fight so I am aiming to work with it, and not against it where possible.

Thanks, the project looks really interesting and currently doing a tester client project with it.

**Comment by gregsullivan** [comment]
Strongly agreed on `theme.json`. I think the main difficulty for custom theme developers right now is knowing which portions of `theme.json` are safe to adopt. As an example, I don't think global styles will ever play nicely with something like Tailwind / _tw. But there's still a lot to like: I use `theme.json` to configure the block editor and to set widths and colours on almost every project, and block-specific settings have been useful for me as well.

This blog post is the one I think of the most when approaching these questions:

https://extendify.com/gutenberg-full-site-editing-does-not-have-to-be-full/

Please let me know if you have any feedback following your test project!
