### ISSUE TITLE
How do I remove the theme.json?

### ISSUE THREAD

**Issue by BlakeXigen** [gregsullivan/_tw#37]
I am looking to remove the theme.json file so that the editor uses the default WordPress styling.

How can I do this without causing issues when running build commands?

**Comment by gregsullivan** [comment]
Hi—Thanks for posting this issue!

Just to confirm, the idea is that you want to continue using the block editor, but without any styling from _tw? Or are you using the classic editor?

(If you're using the block editor, removing the `theme.json` file would have little or no effect on the styling of the editor; it only affects the foreground and background colours.)

**Comment by BlakeXigen** [comment]
Hi,

Thank you for your response!

Yeah thats correct, I want to continue using the block editor without any styling from _tw.

How can I achieve this?

**Comment by gregsullivan** [comment]
I can't test this right now, but you should just need to remove these two lines from `./theme/functions.php`:

https://github.com/gregsullivan/_tw/blob/5dc28069cd79e24f78c4eb7c16943d00e417ee62/theme/functions.php#L81-L82

Please let me know if that works for you!

**Comment by gregsullivan** [comment]
I'm going to close this, but please feel free to respond when you're able, and I'll take a look!
