### ISSUE TITLE
development:esbuild task fails to run on Windows

### ISSUE THREAD

**Issue by beachdbishop** [gregsullivan/_tw#50]
With the recent addition of block-editor.js and the adjustment of the esbuild script, I updated my copy of package.json.

Now, when I run `npm run watch`, I get:

> X [ERROR] Could not resolve "./javascript/*.js"
> 
> It looks like you are trying to use glob syntax (i.e. "*") with esbuild. This syntax is typically handled by your shell, and isn't handled by esbuild itself. You must expand glob syntax first before passing your paths to esbuild.

(FWIW, I'm on Windows 10, running bash in VS Code.)

**Comment by gregsullivan** [comment]
Thanks for this! I'm going to deploy a fix now. In the meantime, you should be able to replace this:

```
./javascript/*.js
```

with this:

```
./javascript/script.js ./javascript/block-editor.js
```

to resolve the problem in your project.

**Comment by beachdbishop** [comment]
Great suggestion! Worked perfectly. Thanks for the fix.

**Comment by gregsullivan** [comment]
No problem at all! I'll share the commit below, in case anyone else ever encounters this:

https://github.com/gregsullivan/_tw/commit/6f908a5d031ff19c7469ea46a27622423d032f63

Thanks again for letting me know, and please let me know if you run into any other issues!
