### ISSUE TITLE
Windows 10 Symbolic Links - Troubleshooting

### ISSUE THREAD

**Issue by bel-caylor** [gregsullivan/_tw#6]
I was trying to setup in a Windows 10 environment following the instructions.  Everything worked exact the symbolic link instructions.  So I wanted to note what finally worked for me so if anyone else using Windows 10 runs into this problem they can find the answer more quickly.
Use this link to download the Link Shell Extension and follow the included directions.
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

Note:  mklink instructions didn't work for me.

Thank you so much for creating this boilerplate.

**Comment by Goodosky** [comment]
Have you tried using `mklink` with the `/J` parameter?
This is a native and simpler solution.

It's what I use:
```mklink /J _sdc ..\..\..\..\_sdc\theme``` (where _sdc is my theme slug)

**Comment by gregsullivan** [comment]
@bel-caylor Does the `/J` parameter work for you?

I don't have access to a Windows 10 environment for testing, but I'd love to add a line to the documentation with Windows 10 instructions. If this line:

`mklink /J [slug] ..\..\..\[slug]\theme`

...works for both of you, I can add something based on that. One day I'd like to have two tabs, one for macOS / Linux and one for Windows 10, but for now I'll just have Windows 10 follow macOS / Linux.

Have either of you required any other changes to get up-and-running? My hope is that using `cross-env` is enough to make things work, but I'd be interested in any and all feedback from Windows users.

**Comment by bel-caylor** [comment]
Thanks @Goodosky that finally worked for me too.  
Here are the directions I would include.
Run the terminal as Administrator and cd to the 'wp-content\themes folder'.
Type
mklink /j {name-of-new-linked-folder-in-theme} ..\{name-of-generated-theme}

**Comment by gregsullivan** [comment]
Perfect, thanks! I'll update the documentation later this week, and I'll post the change here for your feedback.

**Comment by Goodosky** [comment]
@bel-caylor Even simpler is to use a .bat file in the [theme slug] directory (root directory with package.json etc...).

For example:
```bat
cd %CD%
mklink /J ..\wp-content\themes\[theme slug] theme
PAUSE
```

If you use Local WP:
```bat
cd %CD%
mklink /J ..\app\public\wp-content\themes\[theme slug] theme
PAUSE
```

@gregsullivan `cross-env` is enough (I've not observed any problems)

**Comment by gregsullivan** [comment]
@Goodosky Perfect, thanks for letting me know!

@bel-caylor I've added the Windows commands in a similar format to the macOS / Linux ones on the [Getting Started page](https://underscoretw.com/docs/getting-started/). One thing I'm working on is automatically adding the appropriate commands with the theme slug already in place in the readme file; hopefully this is something I'll be able to do soon, easing these issues significantly.

If either of you sees any issues with the documentation as written, or if you run into any Windows-specific issues in the future, please let me know! Thanks again for your help.
