### ISSUE TITLE
Add FSE Support

### ISSUE THREAD

**Issue by AlDeveci** [gregsullivan/_tw#63]
Can you add the "Full Site Editing" support?

**Comment by gregsullivan** [comment]
Hello! Sorry for the delay in responding here—I'm working limited hours this week.

I just wanted to flag two things: One is that many FSE features can be used with hybrid themes (like _tw) already, and more support seems to come online with each new core release. The second is that there is a world in which _tw pivots to support FSE and block themes directly as they mature and WordPress evolves, but I see that as being at least 3–5 years away right now.
