### ISSUE TITLE
Creation of dynamic property WhitelabelOptions::$_title is deprecated

### ISSUE THREAD

**Issue by igorluiza4d** [gregsullivan/_tw#76]
Deprecated: Creation of dynamic property WhitelabelOptions::$_title is deprecated in /wp-content/themes/portal/theme/admin/admin-page.php on line 42

**Comment by beachdbishop** [comment]
Pretty sure ".../admin/admin-page.php" is not part of this repository.

**Comment by gregsullivan** [comment]
Thanks for posting this! Echoing what Daniel said, I can confirm there is not an `admin` folder in the _tw `theme` directory. Is it possible you installed some kind of admin library within your theme?

I'm going to close this issue, but I'd be happy to follow up if there's anything I can do to help.
