### ISSUE TITLE
Wrap run-p value in single quotes to support yarn 2+

### ISSUE THREAD

**Issue by scheinercc** [gregsullivan/_tw#77]
Hey Greg, 
just in case you do want to support yarn at all it seems that for yarn 2+ (v4 just came out hence I remembered to upgrade from v1) `run-p` values need to be wrapped in single quotes, e.g.

```
"watch": "run-p watch:**",
```

becomes
```
"watch": "run-p 'watch:**'",
```

with no issue for `npm`.

Background: https://github.com/mysticatea/npm-run-all/issues/200#issuecomment-1031971521

**Comment by gregsullivan** [comment]
Hey Albert—Thanks for this!

Two quick questions for you:

* What OS are you using?
* Could you do me a favour and try this: `"watch": "run-p \"watch:**\"",`

If both work, I might favour the version with `"` characters given the suggestion that it's compatible with Windows:

https://github.com/mysticatea/npm-run-all/issues/200#issuecomment-1304603313

Would appreciate your thoughts on this!

**Comment by scheinercc** [comment]
Hey Greg!

I am on macOS 14 and `"watch": "run-p \"watch:**\"",` works just as well, so yeah I would say using that makes absolute sense given that comment.

I also tested `"development": "run-p \"development:**\"",` etc.

**Comment by gregsullivan** [comment]
Awesome, thanks for this! I'm working on a minor update for release (potentially today), and this has already been included.

**Comment by gregsullivan** [comment]
Fixed here:

https://github.com/gregsullivan/_tw/commit/8e9f4316b938a5528bad45b900862a844a0a1376

Please let me know if you encounter any other issues with Yarn, specific to `npm-run-all` or otherwise!
