### ISSUE TITLE
Recent update not working with VS Code Tailwind CSS IntelliSense

### ISSUE THREAD

**Issue by S4nG0** [gregsullivan/_tw#88]
Hi there,

I'm having trouble getting the recent _tw theme update to work with the "Tailwind CSS IntelliSense" VS code plugin.

Here's what the output  returns:

> [boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\tailwind\tailwind.config.js] Building...
[Error - 10:52:43 AM] Tailwind CSS: Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at hexToRgb (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\tailwind\tailwind-typography.config.js:3:12)
    at typography (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\tailwind\tailwind-typography.config.js:117:33)
    at value (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:69:41)
    at c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:128:24
    at Array.map (<anonymous>)
    at Object.typography (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:128:15)
    at c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:182:62
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:181:32)
    at resolveConfig (c:\Users\S4nG0\Sites\boudeville-fontaine.fr\boudeville-fontaine.fr\wp-content\themes\boudeville-fontaine\node_modules\tailwindcss\lib\util\resolveConfig.js:248:16)

Any idea as to what could the issue be?

**(Windows 10, running VS Code 1.85.1, Tailwind CSS IntelliSense 0.10.3)**

**Comment by gregsullivan** [comment]
Hello—Thanks for posting this!

This error would definitely show up if the value being passed to `hexToRgb` were undefined. Have you modified the generated theme at all, or did you get this result immediately?

If you renamed the colours in `theme.json` without also renaming them in `tailwind-typography.config.js`, that could cause this issue. I may need to revisit the defaults here to prevent this tripping up anyone else.

As a quick fix, I think you could add this at the beginning of the `hexToRgb` function at the top of `tailwind-typography.config.js`:

```js
if (typeof hex !== 'string' || hex.length === 0) {
	return hex;
}
```

So you'd end up with this:

```js
const hexToRgb = (hex) => {
	if (typeof hex !== 'string' || hex.length === 0) {
		return hex;
	}

	hex = hex.replace('#', '');
	hex = hex.length === 3 ? hex.replace(/./g, '$&$&') : hex;
	const r = parseInt(hex.substring(0, 2), 16);
	const g = parseInt(hex.substring(2, 4), 16);
	const b = parseInt(hex.substring(4, 6), 16);
	return `${r} ${g} ${b}`;
};
```

If you're able to let me know about whether you modified your theme ahead of getting this result, that would be much appreciated!

**Comment by S4nG0** [comment]
Thank you for the help!

It does work with the quick fix to the hexToRgb function.

I could not remember if I made changes to the theme before getting the error, so I tested it with a fresh install and it unfortunately returns the same error even with no changes made to the theme config files.

**Comment by S4nG0** [comment]
It looks like I'm encountering another issues now that I've applied the quickfix.

Seems like all newly-added classes do not get processed. For instance, if I want to use the "items-start" class and I've not used it yet, it does not get processed. Same goes for padding classes (ie "py-6").

Removing the fix and restarting the script does make it work.

**Comment by gregsullivan** [comment]
Just to clarify this part:

> Seems like all newly-added classes do not get processed. For instance, if I want to use the "items-start" class and I've not used it before the fix, it does not get processed. Same goes for padding classes (ie "py-6").

Do you mean that the classes aren't being added to your CSS file, or is this related to IntelliSense?

**Comment by S4nG0** [comment]
Yes I mean classes aren't being added to the CSS file. IntelliSense is working as intended.

**Comment by gregsullivan** [comment]
Could you please confirm that the `watch` process is still running and hasn't crashed? (If it has, please let me know what error you see.)

Does `npm run dev` result in the classes being added?

**Comment by gregsullivan** [comment]
I just generated a new theme, loaded it into VS Code, and autocompletions from Tailwind CSS IntelliSense worked as expected. If this proves to be an ongoing issue, I can try a fresh install on a different computer, as my VS Code setup is somewhat idiosyncratic. (I don't use VS Code for everyday development anymore.)

If anyone else is seeing this issue, I'd love to receive some more reports!

**Comment by S4nG0** [comment]
@gregsullivan It seems I'm not encountering this issue anymore. There might have been an issue with my browser's cache, or the script might have crashed and I didn't notice it. Anyway, seems fine now! Thanks 👍

**Comment by gregsullivan** [comment]
Great, thank you for the update! I'm going to leave this issue open to remind me to add that type check to the `hexToRgb` function, as it would prevent some foreseeable issues.

Thanks again!

**Comment by gregsullivan** [comment]
Out of an abundance of caution, I've added the type check:

https://github.com/gregsullivan/_tw/commit/f5bad85bf8db39dd6f94480dda534e5a94ba946c

Please let me know if you run into any other issues with _tw and Tailwind CSS IntelliSense!
