### ISSUE TITLE
Where to put scripts

### ISSUE THREAD

**Issue by mortennajbjerg** [gregsullivan/_tw#9]
The documentation doesn't really say anything on how to use javascript in your theme.
Is it true that you have to setup webpack/babel etc up manually if you wish to use ES6 or similar?

**Comment by gregsullivan** [comment]
Yes, that's true. The starter theme is meant to be JavaScript-agnostic, in that it doesn't dictate any particular approach. In the next version, I've reinstated the `theme/js` folder and added a `theme/js/vendor` folder with notes indicating what kind of files a developer might put there, but setting up JavaScript build processes will remain outside the scope of _tw.

(My personal approach is to use Alpine.js for the vast majority of my client work, which keeps me from needing a build process almost 100% of the time.)

**Comment by Goodosky** [comment]
I think that's a good approach. There are many ways to build scripts. The theme shouldn't impose its own.

On the other hand, it would be nice to include basic JavaScript configuration in the documentation.

For example, I use esbuild. I've just added a few lines to `scripts` in `package.json`:
```json
"development:js": "esbuild ./scripts/theme-scripts/sdc.js --bundle --outdir=theme/js",
"watch:js": "npm run development:js -- --watch",
"production:js": "npm run development:js -- --minify",
```

**Comment by mortennajbjerg** [comment]
I completely agree with this approach too – but as @Goodosky says, having easy copy-paste-able guidelines in the documentation would be great; especially for us frontend build noobs who have become so dependant on easy out-of-the-box setups :) Thank you for providing your build process @Goodosky. Much appreciated.

**Comment by gregsullivan** [comment]
Works for me! I'll add this to my documentation roadmap. It will likely be along the same lines as the documentation for Browsersync, where it shows one specific implementation, with the idea that it can be adapted for other use cases.

**Comment by gregsullivan** [comment]
I've been revisiting this, and I'm strongly considering adding `esbuild` and having everything hooked up from the start.

Something I'd like to ask everyone participating in this thread: Do you have any opinions on the folder structure? I would like to use `theme/js/script.min.js` as the destination file, and I would like to have the source file(s) in a folder alongside the `tailwind` folder, outside of the theme directory.

There is already a `scripts` folder for build scripts (though there may only ever be one, for creating the zip file).

This is how things look now:

```
generated-theme
├── scripts
├── tailwind
└── theme
```

I was thinking possibly this makes sense:

```
generated-theme
├── javascript
├── npm-scripts
├── tailwind
└── theme
```

What do you think?

**Comment by gregsullivan** [comment]
One further question: Does anyone think it's worth having a default build target (e.g., `es6` or `es2017`), or better to go with the default of `esnext`?

**Comment by mortennajbjerg** [comment]
Sounds great @gregsullivan. I think it makes sense to have this possibility in _tw – at least as an option. The proposed folder structure makes sense to me.

**Comment by gregsullivan** [comment]
I've deployed a new version of _tw with esbuild support. Please see [this commit](https://github.com/gregsullivan/_tw/commit/8f9a2deb3744e142b63aeb68491141a82294315d); if anyone has any comments or concerns, please let me know!

**Comment by productdevbook** [comment]
hi @gregsullivan 

script.js add code but dont theme add scrpite .min.js :/ 

and how to install `Alpine.js` ?

**Comment by gregsullivan** [comment]
You can install Alpine.js by following these instructions:

https://alpinejs.dev/essentials/installation#as-a-module

Put these lines into the `javascript/script.js` file, and that will import and initialize Alpine:

```javascript
import Alpine from 'alpinejs'
 
window.Alpine = Alpine
 
Alpine.start()
```
